### ISSUE TITLE
Test setup does not work

### ISSUE THREAD

**Issue by mhjort** [http-kit/http-kit#251] opened 2016-01-23 15:24 UTC
If I try to run 'lein test' I get following error:

Caused by: java.io.FileNotFoundException: Could not locate clojure/edn__init.class or clojure/edn.clj on classpath:

It seems that the Clojure version (1.4.0) is too old for tests. If I update it to 1.7.0 test setup runs but there is one test that is failing. 

ERROR in (test-websocket-fragmented) (WebSocketClient.java:125)
Uncaught exception, not in assertion.
expected: nil
  actual:                   clojure.main.main                         main.java:   37
                                ...                                        
                  clojure.main/main                          main.clj:  421
              clojure.main/null-opt                          main.clj:  343
            clojure.main/initialize                          main.clj:  308
              clojure.main/init-opt                          main.clj:  280
           clojure.main/load-script                          main.clj:  275
                                ...                                        
                      user/eval1360  form-init3193698749879037593.clj:    1
                   user/eval1360/fn  form-init3193698749879037593.clj:    1
                user/eval1360/fn/fn  form-init3193698749879037593.clj:    1
                user/eval1360/fn/fn  form-init3193698749879037593.clj:    1
                 clojure.core/apply                          core.clj:  630
                                ...                                        
             clojure.test/run-tests                          test.clj:  762
                 clojure.core/apply                          core.clj:  632
                                ...                                        
            clojure.core/merge-with                          core.clj: 2936
               clojure.core/reduce1                          core.clj:  900
               clojure.core/reduce1                          core.clj:  909
                  clojure.core/next                          core.clj:   64
                                ...                                        
                clojure.core/map/fn                          core.clj: 2624
               clojure.test/test-ns                          test.clj:  747
         clojure.test/test-all-vars                          test.clj:  728
             clojure.test/test-vars                          test.clj:  718
   clojure.test/compose-fixtures/fn                          test.clj:  681
       clojure.test/default-fixture                          test.clj:  674
clojure.test/compose-fixtures/fn/fn                          test.clj:  681
   org.httpkit.ws-test/eval10296/fn                       ws_test.clj:   86
          clojure.test/test-vars/fn                          test.clj:  722
       clojure.test/default-fixture                          test.clj:  674
       clojure.test/test-vars/fn/fn                          test.clj:  722
              clojure.test/test-var                          test.clj:  704
           clojure.test/test-var/fn                          test.clj:  704
             org.httpkit.ws-test/fn                       ws_test.clj:  121
org.httpkit.ws.WebSocketClient.ping              WebSocketClient.java:  125
java.lang.Exception: pong frame expected, instead of TextWebSocketFrame(text: abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrst)

Ran 66 tests containing 6834 assertions.
0 failures, 1 errors.
Tests failed.

**Comment by ptaoussanis** [comment] 2016-01-24 02:36
Hi Markus,

> It seems that the Clojure version (1.4.0) is too old for tests. If I update it to 1.7.0 test setup runs but there is one test that is failing.

Thanks for catching this; **PR welcome to bump http-kit's Clojure dep to 1.5.1**.

> ERROR in (test-websocket-fragmented) (WebSocketClient.java:125)

Seems likely that this'll be a result of one of the recent experimental fixes. Someone will need to dig to determine if the test needs updating or if one of the fixes need reverting. I'll try when I have some time again, but not sure when that'll be (might be a couple weeks...).

Thanks for reporting this.

**Comment by mhjort** [comment] 2016-01-24 14:00
Created PR https://github.com/http-kit/http-kit/pull/252

The test I mentioned still fails with thit PR.  I'll try to check using git bisect what commit has broken the test.

**Comment by mhjort** [comment] 2016-01-24 17:59
Found the culprits. Commits 1b08c81e0281bd5bf1cdd7f77f68592f43c5b34a "Fixing fragmented WebSocket messages" and  6f41a5e8698b6dd4be2412e980e415b2bd02a9ba "Fixing opcode reset during PAYLOAD"

I did a quick look and couldn't find the way to fix the problem without reverting. I have to spend some more time on this or then ask help from original author of those commits.

**Comment by ptaoussanis** [comment] 2016-01-25 05:41
Thanks for digging into this, much appreciated!

**Comment by venantius** [comment] 2016-02-26 05:03
I cannot reproduce this. The test run fine (with lots of warnings, to be sure, but with no errors) on my laptop.

**Comment by venantius** [comment] 2016-02-26 05:05
@ptaoussanis, any chance you could take a minute and try running the tests on your machine? I'd like to see how things run on a machine other than mine and @mhjort's

**Comment by ptaoussanis** [comment] 2016-02-26 05:27
Against master:
```
Ran 66 tests containing 6828 assertions.
0 failures, 0 errors.
```

Against `2.1.21-alpha2`:
```
Ran 66 tests containing 6842 assertions.
0 failures, 1 errors.
Tests failed.

ein test org.httpkit.ws-test
#<NullPointerException java.lang.NullPointerException>

lein test :only org.httpkit.ws-test/test-websocket-fragmented

ERROR in (test-websocket-fragmented) (WebSocketClient.java:125)
Uncaught exception, not in assertion.
expected: nil
  actual: java.lang.Exception: pong frame expected, instead of TextWebSocketFrame(text: abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrst)
 at org.httpkit.ws.WebSocketClient.ping (WebSocketClient.java:125)
    org.httpkit.ws_test/fn (ws_test.clj:121)
    clojure.test$test_var$fn__6926.invoke (test.clj:701)
    clojure.test$test_var.invoke (test.clj:701)
    clojure.test$test_all_vars$fn__6930$fn__6937.invoke (test.clj:717)
    clojure.test$default_fixture.invoke (test.clj:671)
    clojure.test$test_all_vars$fn__6930.invoke (test.clj:717)
    org.httpkit.ws_test$eval6631$fn__6632.invoke (ws_test.clj:86)
    clojure.test$compose_fixtures$fn__6920$fn__6921.invoke (test.clj:678)
    clojure.test$default_fixture.invoke (test.clj:671)
    clojure.test$compose_fixtures$fn__6920.invoke (test.clj:678)
    clojure.test$test_all_vars.invoke (test.clj:713)
    clojure.test$test_ns.invoke (test.clj:736)
    clojure.core$map$fn__4087.invoke (core.clj:2434)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:60)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:587)
    clojure.core$next.invoke (core.clj:64)
    clojure.core$reduce1.invoke (core.clj:880)
    clojure.core$reduce1.invoke (core.clj:871)
    clojure.core$merge_with.doInvoke (core.clj:2649)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.core$apply.invoke (core.clj:603)
    clojure.test$run_tests.doInvoke (test.clj:751)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:601)
    user$eval79$fn__136$fn__167.invoke (form-init6577031548438128173.clj:1)
    user$eval79$fn__136$fn__137.invoke (form-init6577031548438128173.clj:1)
    user$eval79$fn__136.invoke (form-init6577031548438128173.clj:1)
    user$eval79.invoke (form-init6577031548438128173.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6511)
    clojure.lang.Compiler.eval (Compiler.java:6501)
    clojure.lang.Compiler.load (Compiler.java:6952)
    clojure.lang.Compiler.loadFile (Compiler.java:6912)
    clojure.main$load_script.invoke (main.clj:283)
    clojure.main$init_opt.invoke (main.clj:288)
    clojure.main$initialize.invoke (main.clj:316)
    clojure.main$null_opt.invoke (main.clj:349)
    clojure.main$main.doInvoke (main.clj:427)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:419)
    clojure.lang.AFn.applyToHelper (AFn.java:163)
    clojure.lang.Var.applyTo (Var.java:532)
    clojure.main.main (main.java:37)
```

**Comment by venantius** [comment] 2016-02-26 05:34
Does this imply there's something on HEAD that fixes the problem?

**Comment by ptaoussanis** [comment] 2016-02-26 05:36
#248?

I'll also note that master seems to be running fewer assertions for some reason (6828 vs 6842) - haven't checked what's going on there, just in the middle of something.

**Comment by venantius** [comment] 2016-02-26 05:41
Mine ran 6825, which suggests they're procedurally / randomly generated. 

Possible that #248 fixes this. In either case, if the problem's resolved on master, I'm going to close this issue.

**Closed by venantius** 2016-02-26 05:41 UTC
Labels: bug?, pull-requests welcome

**Comment by ptaoussanis** [comment] 2016-02-26 05:45
Sounds good.

@mhjort: Hi Markus, please feel free to reopen if you're still running into this against master.

**Comment by mhjort** [comment] 2016-03-01 12:29
Ok. Haven't seen any issues anymore.
