### ISSUE TITLE
OOM error when serializing/deserializing

### ISSUE THREAD

**Issue by danielsz** [http-kit/http-kit#243] opened 2015-12-12 03:59 UTC
Hello, 

Something goes wrong when serializing/deserializing in http-kit + sente, but then an OutOfMemoryError gets thrown. This stops the world. No other recourse than to restart JVM.

I could be wrong, but I think the OOM stems from the way the error is handled, not because actual lack of memory or application code.

Maybe related with #71 

```clojure
2015-12-11_21:22:15.82142 Exception in thread "server-loop" java.lang.OutOfMemoryError: Java heap space
2015-12-11_21:23:02.50629       at java.util.LinkedHashMap.newNode (LinkedHashMap.java:256)
2015-12-11_21:23:02.50633       at java.util.HashMap.putVal (HashMap.java:630)
2015-12-11_21:23:03.63641       at java.util.HashMap.put (HashMap.java:611)
2015-12-11_21:23:03.63645       at sun.util.resources.OpenListResourceBundle.loadLookup (OpenListResourceBundle.java:146)
2015-12-11_21:23:03.63646       at sun.util.resources.OpenListResourceBundle.loadLookupTablesIfNecessary (OpenListResourceBundle.java:128)
2015-12-11_21:23:03.63646       at sun.util.resources.OpenListResourceBundle.handleKeySet (OpenListResourceBundle.java:96)
2015-12-11_21:23:04.43458       at java.util.ResourceBundle.containsKey (ResourceBundle.java:1807)
2015-12-11_21:23:04.43462       at sun.util.locale.provider.LocaleResources.getTimeZoneNames (LocaleResources.java:263)
2015-12-11_21:23:04.43463       at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayNameArray (TimeZoneNameProviderImpl.java:124)
```

**Comment by ptaoussanis** [comment] 2015-12-12 04:08
Hi Daniel,

Will need more information on this, sorry:
1. What version of Sente are you running?
2. What version of http-kit are you running?
3. Have you tried `[com.taoensso.forks/http-kit "2.1.20"]`?
4. Have you confirmed the issue is present with Sente's reference example project?
5. What triggers the error?
6. Do you have reproducible steps or a test case/repo?

Everyone currently involved with http-kit is working with pretty limited time, so the easier you can make looking into an issue the more likely it'll can be looked at in a useful way quickly.

Thanks,

**Comment by danielsz** [comment] 2015-12-12 08:23
Hi Peter, 

Sure, although I'll be sure to disappoint. This is an error that I cannot reproduce locally. It happens in production, with real data, and then only after the system is running perfectly fine for a couple of days. During those days, memory consumption is completely normal, not constantly growing or something like that. The crash take me completely by surprise.

1, Sente  `[com.taoensso/sente "1.6.0"]`
2, Http-kit `[http-kit "2.1.19"]`
3, No. 
4, No.
5, I'm not sure, but I believe it's a faulty package being serialized/deserialized. 
6, Not at this time. 

Because this is an application that runs in production, with real data and real users, my priority is to get rid of the error (rather than understand it), so I decided to swap Immutant instead of http-kit.
Time will tell. I'll update here.

**Comment by ptaoussanis** [comment] 2015-12-12 08:33
Okay, but please note that there won't be much I can do from my end without at least some debug info (observed patterns that trigger the crash, high/low server load, etc.). Indeed, it's not clear to me from the error that you've posted that this even has anything to do with http-kit?

> my priority is to get rid of the error (rather than understand it), so I decided to swap Immutant instead of http-kit.

Sure, understood. Please note though that there's a [known issue](https://github.com/ptaoussanis/sente/issues/150) with Immutant and Sente v1.6.x - you may want to upgrade to v1.7.0+ first.

Good luck!

**Comment by danielsz** [comment] 2015-12-12 08:39
Hi Peter, 

Yes, of course, I understand you can't do much with the current state of information I provided. 
I will update here as soon as new information comes up.
Thanks for the heads up regarding the Immutant issue. :+1:

**Comment by ptaoussanis** [comment] 2015-12-16 03:52
Hi Daniel, going to close this for now (assuming the Immutant move went well?). Please feel free to reopen if you're still experiencing trouble and have identified http-kit as a possible cause. Cheers :-)

**Closed by ptaoussanis** 2015-12-16 03:52 UTC
