### ISSUE TITLE
initial websockets message comes before I get a chance to hook on-receive

### ISSUE THREAD

**Issue by darwin** [http-kit/http-kit#318] opened 2016-12-02 22:08 UTC
I'm a happy user of http-kit. On server I have a http-kit-powered web-sockets server in Clojure and on browser side I have a web-sockets client in ClojureScript. 

The problem is that my implementation is flaky. My app suffers from occasional and very rare situations when initial `:ready` message sent from client to server gets lost. This usually happens in dev scenario where both client and server run on localhost and both processes are cold.

I have a theory what is going wrong and I'm afraid it is a fundamental issue of http-kit API design.

This is my server code:
```clojure
(defn on-new-client-connection [server request]
  (http/with-channel request channel
    (if-not (http/websocket? channel)
      {:status 200 :body "Please connect with a websocket client!"}
      (let [client (make-client channel)]
        (http/on-receive channel (partial add-job! client :receive server client))
        (http/on-close channel (partial add-job! client :close server client))
        (boot-client! server client)))))
```

Imagine that client sends the initial `:ready` message ASAP after opening connection and this Clojure code is slow for some reason. There is a non-zero time window between `with-channel` and `http/on-receive` calls. If message is fast enough and comes before `http/on-receive` it gets silently lost.

Unfortunately it is pretty hard to reproduce this issue in the above code. But obviously the problem can be amplified by putting something like `(Thread/sleep 1000)` before `http/on-receive`.

After reading http-kit code, I believe there is no way how to hook `http/on-receive` to 100% prevent this scenario, because channel is given to the callback after connection has been initiated. And as far as I'm aware there is no "replay" mechanism, which would replay previously received messages after late `http/on-receive` call. 

Ideas?

For reference full implementation is here:
https://github.com/binaryage/dirac/blob/master/src/lib/dirac/lib/ws_client.cljs
https://github.com/binaryage/dirac/blob/master/src/lib/dirac/lib/ws_server.clj

**Comment by zhming0** [comment] 2016-12-07 05:25
In my case, I used normal HTTP URI to transfer the initial message. But it means that the initial message has to be short.

**Comment by marco-nicolini** [comment] 2017-05-02 18:24
I think I'm being hit by this as well in a pet project.
I have the same symptoms: 
- Happens occasionally, especially on cold a server.
- The client (standard browser websocket in js) connects and immediately sends a message (a login message in my case) when the ws connection is opened.

My usage is here https://github.com/marco-nicolini/frothy/blob/master/src/undercover/core.clj

I'm thinking of working around this by changing the application protocol.
I can have the server sending a sort of initial "ready" frame to the client right after the client connects, and only then the client would consider the connection "open" at the application level and start sending messages in. Admittedly it's a workaround and a ugly one at that.

**Comment by lkonstantinov** [comment] 2017-07-21 17:42
We've got bitten some time ago by this and just switched to Immutant due to lack of time to investigate. I've taken a very brief look today, and as far as I can see, the problem is with the `with-channel` macro.

Internally in http-kit you have a read scheduled all the time (after accepting, the socket is registered for reading). When an upgrade request is received, the `with-channel` macro first schedules a write accepting the request and then executes the body, where you would hook your `on-receive` and `on-close` callbacks. What happens is your code gets preempted and before you get a chance to attach the callback the scheduled read is executed, the frame is decoded and then there is no callback to push to :)

Simple fix would be to split `send-websocket-handshake!` into two functions - one doing the header check and another sending the reply and reorder `with-channel`, so the body is executed first (allowing the callbacks to hook) and then sending the reply.

I'll be heading on vacation soon, so dont really have time to do proper testing and PR, but if this approach is acceptable - can do one in late August.

**Comment by huahaiy** [comment] 2019-01-15 00:12
@ptaoussanis I am hit by this problem as well, and I did some investigation. 

The history of this problem seems to be following:  

This problem did not exist in the original version of http-kit around 2013, when the handshake was sent after the macro body. 

Then #14 was filed asking a feature of sending messages before the handshake. So Feng Shen added a queue for these messages to address #14, and added test for this as well.

Then in an attempt to remove the queue to simplify code, Feng Shen changed the order of doing things, and this problem was introduced since 25c361888c5baed49842e30e151899be84f33ee8.

So there are two options to fix this problem:

1. Put the queue back. This seems to be complicated and may have performance implication.

2. Follow @lkonstantinov 's suggestion, and revert the order to original version, where the macro body is evaluated before sending the handshake. This will break the test for #14, and effectively removes that feature. 

I favor option 2. Because it is rather unusual for the server to send messages before the handshake is established. Normally, it is the client that initiates the WebSocket collection, and the client expect to immediately start sending messages when the handshake is received. This is a much more common use case. The unusual use case should simply be dropped. The person who file #14 is no longer working with Clojure anyway.

@ptaoussanis option 2 is acceptable for you, I can send in a PR.

**Comment by ptaoussanis** [comment] 2019-01-18 08:16
Hi @huahaiy, thank you so much for the analysis and clear report- that's very helpful. Looking at the PR now 👍

**Comment by ptaoussanis** [comment] 2019-01-18 09:17
@huahaiy Have merged, and made [some tweaks](https://github.com/http-kit/http-kit/commit/7bc84f4e7919d9a4b79d1c1e0269e35d3bba657a) to the PR - requesting your review.

Thanks!

**Comment by ptaoussanis** [comment] 2019-03-23 09:40
Requesting review of #396. The relevant code is [here](https://github.com/http-kit/http-kit/blob/d0109a34afb386d617b57bfde986e28f1b962303/src/org/httpkit/server.clj#L210).

Basically this PR deprecates the `with-channel` macro, and introduces an `as-channel` function.

The function takes explicit optional handlers: `{:keys [on-receive on-ping on-close on-open on-handshake-error]}`. It just ensures receive, ping, and close handlers are established _before_ WebSocket handshake; and open handler is fired _after_.

It's a simple-enough change (and a simple function), but would mean:

1. Deprecating `with-channel`, which will be disruptive (incl. making docs + examples obsolete).
2. Leaving `with-channel` with the previous potential race condition for folks who don't migrate.

Would be ideal to have a solution where we could mod `with-channel` in a way that both removes the race and doesn't break anyone depending on #14 - but as @huahaiy observed that might need us to re-introduce a queue and the related complexity. Would be open to a PR though if someone had time to investigate and bench.

Otherwise, motivations for the current PR:

- I believe the race in #2 is fairly rare, and mostly observed in dev/testing - so #2 might be less disruptive than reverting #14 (which can cause outright breakages, as in [here](https://github.com/ptaoussanis/sente/issues/336)).
- The migration from `with-channel` to `as-channel` is quite minor - and purely syntactic; I don't expect anyone to need any logical or architectural changes.

Pretty short on time, so wasn't able to look at this long - any+all feedback very welcome.

cc @huahaiy

**Comment by darwin** [comment] 2019-03-23 13:14
I would recommend during `with-channel` macroexpansion to emit a call to some dummy function which would be marked as ^:deprecated. This way compiler should emit a warning when compiling code with `with-channel` usage. That could be enough to bring attention to its docstring with further explanation.

**Comment by huahaiy** [comment] 2019-03-23 21:05
Agreed.

**Comment by lkonstantinov** [comment] 2020-06-23 11:09
Hi,

I just had time to look at `as-channel` and unfortunately the implementation is still broken. The problem is that `send-checked-websocket-handshake!` is called before the open handler, so even though the read handler is registered, you still can get (and we do indeed get) a race condition.

Consider the example that is listed in the method itself:

```
    (def clients_ (atom #{}))
    (defn my-async-handler [ring-req]
      (as-channel ring-req
        {:on-open (fn [ch] (swap! clients_ conj ch))}))
```
The `clients_` atom wont be updated before the first read arrives, so if you have any information associated with the channel, it wont be available to your read handler.

A fix would be to rewrite the code as this:

```
(do
          (when-let [f on-receive] (org.httpkit.server/on-receive ch (partial f ch)))
          (when-let [f on-ping]    (org.httpkit.server/on-ping    ch (partial f ch)))
          (when-let [f on-open] (f ch))
          (send-checked-websocket-handshake! ch sec-ws-accept))
```

**Comment by ptaoussanis** [comment] 2020-06-23 11:33
@lkonstantinov Thanks for taking a look, and for the feedback.

I only have a moment to look at this, and it's been a while since I've looked at it - so apologies if I'm missing anything  obvious.

To clarify: `on-open`'s purpose is described as:
>  called when AsyncChannel is ready for `send!`

So doing the handshake _after_ `on-open` is called won't work unless we do something like introduce a queue as discussed [here](https://github.com/http-kit/http-kit/issues/318#issuecomment-475855529).

I understood your [original comments](https://github.com/http-kit/http-kit/issues/318#issuecomment-317066263) to mean that the race condition you were concerned about was the handshake happening before you could assign an `on-receive` handler? This fits the initial issue description, and it's clear why this would be a problem.

It's less immediately clear to me why you'd want `on-open` to be called before handshake. (Again, might be missing something obvious).

Not sure I follow what you'd be trying to do in your example:

> The clients_ atom wont be updated before the first read arrives, so if you have any information associated with the channel, it wont be available to your read handler.

To make sure I'm understanding properly, could you maybe give a more concrete example of where you think there may still be a problem with the current implementation of `as-channel`?

Thanks!

**Comment by lkonstantinov** [comment] 2020-06-23 11:54
Sure - imagine you have this oversimplified example:

```
(def clients_ (atom {}))

(defn metadata-for-channel [ch] ...)
(defn foo [metadata data] ...)

(defn my-async-handler [ring-req]
  (as-channel ring-req
              {:on-open (fn [ch] (swap! clients_ assoc (metadata-for-channel ch)))
               :on-receive (fn [ch data]
                             (if-let [metadata (get @clients_ ch)]
                               (foo metadata data)
                               (timbre/error "race condition")))}))
```

The current implementation triggers `on-receive` before `on-open` is completed, so it breaks the proper (imho) lifecycle of `on-open` `on-receive `on-close`. One can argue that you can perform the initialization in `on-receive` but this will make the code more unwieldy.

**Comment by ptaoussanis** [comment] 2020-06-23 16:54
@lkonstantinov 👍  Requesting your input on https://github.com/http-kit/http-kit/commit/f77640daaa64d08f49022902ead3a7e5a07e86aa when you have a moment, thanks!

**Comment by lkonstantinov** [comment] 2020-06-23 17:16
Thanx @ptaoussanis - looks good to me :)

Being the lazy person that I am, I would've probably left the existing interface in and just added the `:init` key.

**Comment by ptaoussanis** [comment] 2020-06-23 18:03
Actually, that makes more sense if we're anyway going to still support the deprecated hooks. Let's just keep it simple, and the change minimal. Adjusted.

**Comment by ptaoussanis** [comment] 2020-07-30 10:53
Closing with the release of `[http-kit "2.4.0"]` - thanks to everyone for all the efforts on this issue!

**Closed by ptaoussanis** 2020-07-30 10:53 UTC
Labels: bug?, ideas welcome, needs investigation, pull-requests welcome, server
