### ISSUE TITLE
ConcurrentModificationException in HttpServer.stop

### ISSUE THREAD

**Issue by marcomorain** [http-kit/http-kit#218] opened 2015-06-23 10:16 UTC
I'm currently trying to track down the cause of this exception:

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:196)
	at java.util.Collections$UnmodifiableCollection.toArray(Collections.java:1034)
	at org.httpkit.server.HttpServer.stop(HttpServer.java:310)
	at org.httpkit.server$run_server$stop_server__89493.doInvoke(server.clj:31)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.core$trampoline.invoke(core.clj:5801)
	at circle.util.retry$wait_for.doInvoke(retry.clj:174)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at circle.test.util.thread$block_web_requests.invoke(thread.clj:77)
<snipped>
```

I'm not sure if it's a problem on our end or with http-kit, but I thought I would open this issue incase anyone else has seen the problem.

Using `[http-kit "2.1.18"]`

**Comment by songsd** [comment] 2015-06-24 04:14
I guess that's because you call "stop()" in another thread.While selector.keys().toArray() is called,in the server thread some new channel is registered to the selector. ConcurrentModificationException is thrown because the set is changed while iterating.

**Comment by marcomorain** [comment] 2015-06-25 09:59
@songsd I don't think there is anything that I can do in this case. When I start the server with `run-server` I just have a reference the stop function, and no other access to the server object. The server thread is still serving requests when I call stop, and there is nothing that I can do about that.

**Comment by marcomorain** [comment] 2015-06-25 10:00
I'm pretty sure that this is a bug in `http-kit` and there is no way to work around this issue from client code.

**Comment by marcomorain** [comment] 2015-06-25 10:31
Should the code be waiting for the  returned by [`serverChannel.close()`](http://netty.io/4.0/api/io/netty/channel/Channel.html#close()) to be be complete?

**Comment by songsd** [comment] 2015-06-26 01:06
I think it's a bug too.Even "serverChannel.close()" is called or the Future is completed,some selectorKey may be removed from the set when iterating the array,the ConcurrentModificationException may be thrown.

**Comment by songsd** [comment] 2015-06-26 01:24
If you can't ignore the Exception,I guess may be some ways to solve the problem:

1 ,add some synchronized code when the keyset will be changing.

2,move accept(read,write) logic to AcceptHandler,when trying to stop ,set the handler to StopHander.

3,modify the way to stop the server.Just interupt the sever to let the server notice the interupt and stop by itself.

**Comment by ptaoussanis** [comment] 2015-12-12 04:24
Hi there, performing issue triage - is this issue still relevant?

**Comment by ptaoussanis** [comment] 2015-12-13 10:39
Closing as a duplicate of https://github.com/http-kit/http-kit/issues/82

**Closed by ptaoussanis** 2015-12-13 10:39 UTC
