### ISSUE TITLE
Support sending Cookies in the HTTP client

### ISSUE THREAD

**Issue by one-more-minute** [http-kit/http-kit#158] opened 2014-08-11 02:03 UTC
Support for cookies similar to clj-http would be great to have.

**Comment by wxjeacen** [comment] 2015-03-23 09:27
I am also looking forward on cookies supporting in this project.

**Comment by fgerard** [comment] 2015-07-13 23:19
Yes please adding cookies is needed to do a chain of invocations with session for example

**Comment by ptaoussanis** [comment] 2015-12-13 10:00
Hi there, closing as a duplicate of #109

**Closed by ptaoussanis** 2015-12-13 10:00 UTC
