### ISSUE TITLE
Unexpected body of `head` request for `image/svg+xml` resource

### ISSUE THREAD

**Issue by kirillsalykin** [http-kit/http-kit#425] opened 2020-02-02 10:40 UTC
When doing `head` request for a resource with type `image/png` - the body is an empty stream.
but for resource `image/svg+xml` the body is empty string `""`.

Expected is an empty stream as well.

**Comment by ptaoussanis** [comment] 2023-11-02 10:04
Closing as a duplicate of https://github.com/http-kit/http-kit/issues/366

**Closed by ptaoussanis** 2023-11-02 10:04 UTC
Labels: ideas welcome, client
