### ISSUE TITLE
Slow consumer can exhaust memory on Server

### ISSUE THREAD

**Issue by BarelyFunctional** [http-kit/http-kit#180] opened 2014-12-08 12:03 UTC
I've written a server using httpkit which streams a large amount of data to the client. If the Client cannot consume the data fast enough, or the network is the bottleneck, I get an OOM on the server. A cursory examination appears the culprit is:

https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/server/HttpServer.java#L47

The server uses an unbounded queue which means there is no backpressure mechanism. Would it be possible to change for a bounded queue mechanism where writes to the channel block when the queue is full?

**Comment by ptaoussanis** [comment] 2015-12-13 10:43
Closing as duplicate of https://github.com/http-kit/http-kit/issues/90

**Closed by ptaoussanis** 2015-12-13 10:43 UTC
Labels: enhancement
