### ISSUE TITLE
 Session disappears with redirect

### ISSUE THREAD

**Issue by elect000** [http-kit/http-kit#378] opened 2018-06-03 16:32 UTC
https://github.com/MokkeMeguru/redirect-session-errors

namespace : redirect-session-errors.routes.home

```
   ["/door" {:get {:handler (fn [_]
                              (let [send-message (-> (ring.util.response/redirect "/room") 
                                                     (assoc-in [:session :identity] :key))] ;; add session
                                (println "send-message\n"
                                         send-message)
                                send-message))}}]
   ["/room" {:get {:handler (fn [req]
                              (println "receive-message\n" ;; I hope to find "session" here
                                       req)
                              (home-page req))}}]
```

But

```
send-message
 {:status 302, :headers {Location /room}, :body , :session {:identity :key}}
receive-message
 {:reitit.core/match #reitit.core.Match{:template /room, :data {:middleware [#function[redirect-session-errors.middleware/wrap-base]], :get {:handler #function[redirect-session-errors.routes.home/home-routes/fn--31254]}}, :result #reitit.ring.Methods{:get #reitit.ring.Endpoint{:data {:middleware [#function[redirect-session-errors.middleware/wrap-base]], :handler #function[redirect-session-errors.routes.home/home-routes/fn--31254]}, :handler #function[redirect-session-errors.middleware/wrap-internal-error/fn--31221], :path /room, :method :get, :middleware [#reitit.middleware.Middleware{:name nil, :wrap #function[redirect-session-errors.middleware/wrap-base], :spec nil}]}, :head nil, :post nil, :put nil, :delete nil, :connect nil, :options nil, :trace nil, :patch nil}, :path-params {}, :path /room}, :reitit.core/router #object[reitit.core$lookup_router$reify__32013 0x70c92097 reitit.core$lookup_router$reify__32013@70c92097], :cookies {JSESSIONID {:value zGYyHu24MS_SFbI4--gbWB_IVQJqrvyTg1jqqMbV}, 
ring-session {:value 22f2392c-3861-4863-bf8d-639dcee0b9cd}}, :remote-addr 0:0:0:0:0:0:0:1, :params {}, :flash nil, :headers {accept text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8, accept-encoding gzip, deflate, br, accept-language ja,en-US;q=0.9,en;q=0.8,pt;q=0.7,fr;q=0.6, connection keep-alive, cookie JSESSIONID=zGYyHu24MS_SFbI4--gbWB_IVQJqrvyTg1jqqMbV; ring-session=22f2392c-3861-4863-bf8d-639dcee0b9cd, host localhost:3000, upgrade-insecure-requests 1, user-agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36}, :async-channel #object[org.httpkit.server.AsyncChannel 0x411eee1b /0:0:0:0:0:0:0:1:3000<->/0:0:0:0:0:0:0:1:38828], :server-port 3000, :content-length 0, :form-params {}, :websocket? false, :session/key nil, :query-params {}, :content-type nil, :character-encoding utf8, :uri /room, :server-name localhost, :query-string nil, :path-params {}, :body nil, :multipart-params {}, :scheme :http, :request-method :get
, :session {}}
```

**Comment by Ramblurr** [comment] 2020-08-13 10:19
:exclamation: :exclamation: Been debugging for hours and I've finally landed on this issue.

My login handler sets the session and redirects, and *poof* the session is gone. This isn't being seen by anyone else?

**Comment by msouce** [comment] 2021-04-26 21:21
Has anyone hit upon a fix or more concrete cause for this?

Setting the session on the response of a 302 redirect, but on handling the redirect the session object is unexpectedly empty.

**Comment by ptaoussanis** [comment] 2021-04-27 06:58
Would be happy to take a look at a minimal reproducible example if someone could please provide one 👍

**Comment by MokkeMeguru** [comment] 2021-04-28 09:56
https://github.com/MokkeMeguru/redirect-session-errors i think it's simple but i need to version up. wait a moment please

**Comment by ptaoussanis** [comment] 2021-04-30 10:33
@MokkeMeguru Hi Mokke! Would please request a smaller reproducible example without the use of a framework, or so many dependencies and namespaces.

If there's a fundamental problem with sessions during redirect, I suspect that it should likely be possible to show that in a single namespace with ~<30 lines of code.

The motivations for having a smaller repro:

1. It's quicker for me (and/or others) to inspect + understand. Which means you'll likely get a response quicker.
2. It rules out the possibility of problems being introduced by frameworks, middleware, etc. Particularly relevant here since those are very plausible causes of problems.
3. It makes it easier to drop in an alternative HTTP server (e.g. Jetty) to see whether that resolves the problem (which'd be evidence to suggest that the problem is indeed on http-kit's side).

Hope that makes sense, thanks!

**Closed** 2023-05-30 09:36 UTC
Labels: question/usage
