### ISSUE TITLE
Deflate-frame support

### ISSUE THREAD

**Issue by galdolber** [http-kit/http-kit#50] opened 2013-05-13 22:15 UTC
Is there any plan to support the deflate extension?

Sec-WebSocket-Extensions:x-webkit-deflate-frame

**Comment by brunchboy** [comment] 2015-06-20 20:08
I wonder if browsers are starting to expect this? I can’t get WebSocket connections to work to http-kit. In Safari attempts result in: `[Error] WebSocket connection to 'ws://localhost:16000/ws' failed: Compressed bit must be 0 if no negotiated deflate-frame extension (1, line 0)`, and in Chrome I see: `WebSocket connection to 'ws://localhost:16000/ws' failed: Invalid frame header`. So for now I have to give up on the idea of WebSockets, and just have my page poll for new data frequently.

**Comment by pate** [comment] 2015-08-19 10:35
@brunchboy I followed the sente README to the letter, and I'm also getting the exact same errors in Chrome and Safari.

**Comment by brunchboy** [comment] 2015-08-19 14:42
I’d love for this to work, so I can stop wasting (albeit small amounts of) CPU polling every 30ms.

**Comment by pate** [comment] 2015-08-19 14:58
@brunchboy my problem was caused by ring middleware.

**Comment by brunchboy** [comment] 2015-08-19 15:10
Oh, really? Which piece of middleware, and how were you able to resolve it?

**Comment by brunchboy** [comment] 2015-12-13 19:17
I really wish I were able to use this functionality. @pate can you tell me what middleware was the issue and how you resolved it?

**Comment by ptaoussanis** [comment] 2015-12-16 04:26
@pate or anyone else have any input on this? Thanks!

**Comment by brunchboy** [comment] 2015-12-16 15:50
Even if not, I don’t think it was inappropriate of you to close the issue, if @pate is correct, the problem is not with http-kit.

**Comment by ptaoussanis** [comment] 2016-03-02 03:53
@brunchboy Thanks!

**Closed by ptaoussanis** 2016-03-02 03:53 UTC
