### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by olessavluk** [http-kit/http-kit#334] opened 2017-04-30 15:13 UTC
Hi,
What is the current support for HTTPS?
I've received some errors when tried to make request:

✅  https://www.google.com.ua/

<br>
⛔  https://clojure.org
<details>
<summary>Received fatal alert: handshake_failure</summary>

```
#error {
 :cause Received fatal alert: handshake_failure
 :via
 [{:type javax.net.ssl.SSLException
   :message Received fatal alert: handshake_failure
   :at [sun.security.ssl.Alerts getSSLException Alerts.java 208]}]
 :trace
 [[sun.security.ssl.Alerts getSSLException Alerts.java 208]
  [sun.security.ssl.SSLEngineImpl fatal SSLEngineImpl.java 1666]
  [sun.security.ssl.SSLEngineImpl fatal SSLEngineImpl.java 1634]
  [sun.security.ssl.SSLEngineImpl recvAlert SSLEngineImpl.java 1800]
  [sun.security.ssl.SSLEngineImpl readRecord SSLEngineImpl.java 1083]
  [sun.security.ssl.SSLEngineImpl readNetRecord SSLEngineImpl.java 907]
  [sun.security.ssl.SSLEngineImpl unwrap SSLEngineImpl.java 781]
  [javax.net.ssl.SSLEngine unwrap SSLEngine.java 624]
  [org.httpkit.client.HttpsRequest doHandshake HttpsRequest.java 98]
  [org.httpkit.client.HttpClient doRead HttpClient.java 139]
  [org.httpkit.client.HttpClient run HttpClient.java 426]
  [java.lang.Thread run Thread.java 745]]}
```
</details>

<br>
⛔  https://letsencrypt.org
(works fine with OpenJDK)
<details>
<summary>unable to find valid certification path to requested target</summary>

```
#error {
 :cause unable to find valid certification path to requested target
 :via
 [{:type javax.net.ssl.SSLHandshakeException
   :message General SSLEngine problem
   :at [sun.security.ssl.Handshaker checkThrown Handshaker.java 1431]}
  {:type javax.net.ssl.SSLHandshakeException
   :message General SSLEngine problem
   :at [sun.security.ssl.Alerts getSSLException Alerts.java 192]}
  {:type sun.security.validator.ValidatorException
   :message PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   :at [sun.security.validator.PKIXValidator doBuild PKIXValidator.java 387]}
  {:type sun.security.provider.certpath.SunCertPathBuilderException
   :message unable to find valid certification path to requested target
   :at [sun.security.provider.certpath.SunCertPathBuilder build SunCertPathBuilder.java 146]}]
 :trace
 [[sun.security.provider.certpath.SunCertPathBuilder build SunCertPathBuilder.java 146]
  [sun.security.provider.certpath.SunCertPathBuilder engineBuild SunCertPathBuilder.java 131]
  [java.security.cert.CertPathBuilder build CertPathBuilder.java 280]
  [sun.security.validator.PKIXValidator doBuild PKIXValidator.java 382]
  [sun.security.validator.PKIXValidator engineValidate PKIXValidator.java 292]
  [sun.security.validator.Validator validate Validator.java 260]
  [sun.security.ssl.X509TrustManagerImpl validate X509TrustManagerImpl.java 324]
  [sun.security.ssl.X509TrustManagerImpl checkTrusted X509TrustManagerImpl.java 281]
  [sun.security.ssl.X509TrustManagerImpl checkServerTrusted X509TrustManagerImpl.java 136]
  [sun.security.ssl.ClientHandshaker serverCertificate ClientHandshaker.java 1496]
  [sun.security.ssl.ClientHandshaker processMessage ClientHandshaker.java 216]
  [sun.security.ssl.Handshaker processLoop Handshaker.java 979]
  [sun.security.ssl.Handshaker$1 run Handshaker.java 919]
  [sun.security.ssl.Handshaker$1 run Handshaker.java 916]
  [java.security.AccessController doPrivileged AccessController.java -2]
  [sun.security.ssl.Handshaker$DelegatedTask run Handshaker.java 1369]
  [org.httpkit.client.HttpsRequest doHandshake HttpsRequest.java 89]
  [org.httpkit.client.HttpClient doRead HttpClient.java 139]
  [org.httpkit.client.HttpClient run HttpClient.java 426]
  [java.lang.Thread run Thread.java 745]]}
```
</details>

<br>
⛔  https://httpbin.org/get
<details>
<summary>Received fatal alert: internal_error</summary>

```
#error {
 :cause Received fatal alert: internal_error
 :via
 [{:type javax.net.ssl.SSLException
   :message Received fatal alert: internal_error
   :at [sun.security.ssl.Alerts getSSLException Alerts.java 208]}]
 :trace
 [[sun.security.ssl.Alerts getSSLException Alerts.java 208]
  [sun.security.ssl.SSLEngineImpl fatal SSLEngineImpl.java 1666]
  [sun.security.ssl.SSLEngineImpl fatal SSLEngineImpl.java 1634]
  [sun.security.ssl.SSLEngineImpl recvAlert SSLEngineImpl.java 1800]
  [sun.security.ssl.SSLEngineImpl readRecord SSLEngineImpl.java 1083]
  [sun.security.ssl.SSLEngineImpl readNetRecord SSLEngineImpl.java 907]
  [sun.security.ssl.SSLEngineImpl unwrap SSLEngineImpl.java 781]
  [javax.net.ssl.SSLEngine unwrap SSLEngine.java 624]
  [org.httpkit.client.HttpsRequest doHandshake HttpsRequest.java 98]
  [org.httpkit.client.HttpClient doRead HttpClient.java 139]
  [org.httpkit.client.HttpClient run HttpClient.java 426]
  [java.lang.Thread run Thread.java 745]]}
```
</details>

### Environment
<details>
 
http-kit "2.2.0"
 
 Leiningen 2.7.1 on Java 1.8.0_66 Java HotSpot(TM) 64-Bit Server VM

 java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

 Mac OS X 10.11.4 (15E65)
</details>

### How to reproduce?
see https://github.com/olessavluk/httpkit-ssl-issue

**Comment by olessavluk** [comment] 2017-04-30 15:19
I've also tried to use custom `ssl-engine`, as described in this issue https://github.com/http-kit/http-kit/issues/228
And it worked fine only for letsencrypt site, all others have failed:
<details>
⛔  https://www.google.com.ua/?gfe_rd=cr&ei=AAAGWYbwMcPR8geN_5GYBA

```
#error {
 :cause invalid AEAD cipher fragment
 :via
 [{:type javax.net.ssl.SSLException
   :message invalid AEAD cipher fragment
   :at [sun.security.ssl.Alerts getSSLException Alerts.java 208]}
  {:type javax.crypto.BadPaddingException
   :message invalid AEAD cipher fragment
   :at [sun.security.ssl.CipherBox applyExplicitNonce CipherBox.java 927]}]
 :trace
 [[sun.security.ssl.CipherBox applyExplicitNonce CipherBox.java 927]
  [sun.security.ssl.CipherBox applyExplicitNonce CipherBox.java 983]
  [sun.security.ssl.InputRecord decrypt InputRecord.java 157]
  [sun.security.ssl.EngineInputRecord decrypt EngineInputRecord.java 177]
  [sun.security.ssl.SSLEngineImpl readRecord SSLEngineImpl.java 974]
  [sun.security.ssl.SSLEngineImpl readNetRecord SSLEngineImpl.java 907]
  [sun.security.ssl.SSLEngineImpl unwrap SSLEngineImpl.java 781]
  [javax.net.ssl.SSLEngine unwrap SSLEngine.java 624]
  [org.httpkit.client.HttpsRequest doHandshake HttpsRequest.java 98]
  [org.httpkit.client.HttpClient doRead HttpClient.java 139]
  [org.httpkit.client.HttpClient run HttpClient.java 426]
  [java.lang.Thread run Thread.java 745]]}
```

⛔  https://clojure.org
```
#error {
 :cause SSLEngine is closing/closed
 :via
 [{:type javax.net.ssl.SSLException
   :message SSLEngine is closing/closed
   :at [sun.security.ssl.SSLEngineImpl kickstartHandshake SSLEngineImpl.java 713]}]
 :trace
 [[sun.security.ssl.SSLEngineImpl kickstartHandshake SSLEngineImpl.java 713]
  [sun.security.ssl.SSLEngineImpl beginHandshake SSLEngineImpl.java 756]
  [org.httpkit.client.HttpClient finishConnect HttpClient.java 347]
  [org.httpkit.client.HttpClient run HttpClient.java 424]
  [java.lang.Thread run Thread.java 745]]}
```
...
</details>

**Comment by bertofer** [comment] 2017-07-29 21:12
I have the same problem trying to access https://www.alphavantage.co/documentation/

This is the error:

```
{:opts {:method :get, :url "https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=MSFT&interval=1min&apikey=demo"}, :error #error { 
 :cause "Received fatal alert: internal_error" 
 :via 
 [{:type javax.net.ssl.SSLException 
   :message "Received fatal alert: internal_error" 
   :at [sun.security.ssl.Alerts getSSLException "Alerts.java" 208]}] 
 :trace 
 [[sun.security.ssl.Alerts getSSLException "Alerts.java" 208] 
  [sun.security.ssl.SSLEngineImpl fatal "SSLEngineImpl.java" 1666] 
  [sun.security.ssl.SSLEngineImpl fatal "SSLEngineImpl.java" 1634] 
  [sun.security.ssl.SSLEngineImpl recvAlert "SSLEngineImpl.java" 1800] 
  [sun.security.ssl.SSLEngineImpl readRecord "SSLEngineImpl.java" 1083] 
  [sun.security.ssl.SSLEngineImpl readNetRecord "SSLEngineImpl.java" 907] 
  [sun.security.ssl.SSLEngineImpl unwrap "SSLEngineImpl.java" 781] 
  [javax.net.ssl.SSLEngine unwrap "SSLEngine.java" 624] 
  [org.httpkit.client.HttpsRequest doHandshake "HttpsRequest.java" 98] 
  [org.httpkit.client.HttpClient doRead "HttpClient.java" 139] 
  [org.httpkit.client.HttpClient run "HttpClient.java" 426] 
  [java.lang.Thread run "Thread.java" 745]]}} 

 

```

**Comment by aeriksson** [comment] 2017-12-18 15:26
So I tried @olessavluk's example with http-kit `2.3.0-alpha4`. https://letsencrypt.org seems to work now, while https://clojure.org and https://httpbin.org/get fail with the same errors as before.

Does anyone have idea what's causing these errors, or how to fix them?

**Comment by jiacai2050** [comment] 2017-12-25 01:49
I can't reproduce this issue with 2.3.0-alpha4.

```
(def test-urls ["https://httpbin.org/get"
                "https://letsencrypt.org/"       
                "https://clojure.org"])

(defn sni-configure
  [^SSLEngine ssl-engine ^URI uri]
  (let [^SSLParameters ssl-params (.getSSLParameters ssl-engine)]
    (.setServerNames ssl-params [(SNIHostName. (.getHost uri))])
    (.setSSLParameters ssl-engine ssl-params)))

(def client (http/make-client {:ssl-configurer sni-configure}))

(defn test-ssl [url]
  (let [{:keys [status headers body error] :as resp} @(http/head url {:client client})]
    (if error
      (println url " Failed, exception: " error)
      (println url " HTTP GET success: " status))))

(mapv test-ssl test-urls)
```

**Comment by ptaoussanis** [comment] 2018-02-02 20:49
Is this still an issue after @jiacai2050's positive results with `2.3.0-alpha4`? Or can this be closed?

Thanks!

**Comment by olessavluk** [comment] 2018-02-04 18:12
Yes, it works, but only for the client created with custom `:ssl-configurer sni-configure` option passed, not with the default one.

@ptaoussanis does it make sense to replace the default/empty [`SSLEngineURIConfigurer` implementation](https://github.com/http-kit/http-kit/blob/5ec311563ec7c9088f7129b0cdfeae29c2361b02/src/java/org/httpkit/client/HttpClient.java#L72) with the snippet provided by @jiacai2050 so that the default client will also work?

**Comment by kumarshantanu** [comment] 2018-02-04 18:55
@olessavluk AFAIK the SNI-related classes appeared only in Java 8, so to make that work by default HTTP-Kit would have to drop support for Java 7 and below, which seems unlikely at this time due to Clojure's support for older JVMs.

**Comment by Jell** [comment] 2018-08-07 04:39
Regarding SNI support and backward compatibility as per @kumarshantanu’s comment, clojure 1.10 will drop support for java 6 & 7 anyway, perhaps time to drop support here as well and make the http client work with SNI certs by default?

For reference: neither certs from cloudflare nor amazon’s cloudfront are supported by the client by default, and the work-around with :ssl-configurer requires changing every single http client call location (we replaced some of our certs at Zimpler with a clouflare provided one and we had to basically refactor all our projects in a quite intrusive way to get the workaround in place)

**Comment by ptaoussanis** [comment] 2020-01-04 10:45
Closing since an SNI-capable client is now provided out-the-box as part of `2.4.0-alpha5`. Will try cut a documented beta release next week, just waiting on some tests to be added.

**Closed by ptaoussanis** 2020-01-04 10:45 UTC
Labels: assistance welcome, can close?, client
