### ISSUE TITLE
SSL validation broken on  2.4.0-alpha3

### ISSUE THREAD

**Issue by jimpil** [http-kit/http-kit#417] opened 2019-10-14 12:59 UTC
Hi folks,

I was investigating some weird behaviour at work, and that led me to #316 and of course to #344. After doing some testing, I can confirm that `2.2.0` and `2.3.0` work as expected for all those _badssl_ URLs. On the contrary, `2.4.0-alpha3` allows all of them! I've tested this on jdk8, and since the 2.4 version is the only version compatible with versions greater than 8, I can't really compare anything else. But for now this pretty much forces us to stay on jdk8 :(.

A quick skim-through the changelog doesn't reveal anything obvious - i will have to dive deepper...

**Comment by ptaoussanis** [comment] 2020-01-04 10:50
Closing as an apparent dupe of https://github.com/http-kit/http-kit/issues/344. PR/s welcome on that issue.

Thanks!

**Closed by ptaoussanis** 2020-01-04 10:50 UTC
